name: Set Up

description: Install Zig, Alpine, libgit2, zlib, libclang

runs:
  using: composite
  steps:
    - name: Setup Alpine
      shell: sh
      run: |
        apk update
        apk add ninja-build nodejs cmake wget tar samurai xz just make gzip bash git shadow curl

    - name: Setup Nix
      shell: bash
      run: |
        sh <(curl -L https://nixos.org/nix/install) --daemon --yes

    - name: Check Nix
      shell: bash
      run: |
        sudo nix-daemon
        nix-shell -p nix-info --run "nix-info -m"

    - name: Configure Nix
      shell: bash
      run: |
        mkdir -p ~/.config/nix
        echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

    - uses: goto-bus-stop/setup-zig@v2.2.0

    - name: Check Zig ENV
      shell: bash
      run: zig env

    - name: Install libclang and static binaries
      shell: bash
      run: |
        apk add clang17-dev clang17-static musl-dev libc++-dev libc++-static openssl-dev clang17-analyzer
        echo "CC=clang-17" >> $GITHUB_ENV
        echo "CXX=clang++-17" >> $GITHUB_ENV

    - name: Build libgit2, zlib
      shell: bash
      run: |
        just install-libgit2 && just build-libgit2
        just install-zlib && just build-zlib

    - name: Run zig fmt
      shell: bash
      run: zig fmt --check .


