name: Set Up
description: Install Zig, Alpine, libgit2, zlib, libclang
runs:
  using: composite
  steps:
    - name: Setup Base ENV
      shell: sh
      run: |
        sudo apt-get update
        sudo apt-get install wget tar gzip bash git curl file autoconf automake cmake ninja-build libzstd-dev build-essential libc++-dev libstdc++-11-dev llvm-dev libclang-dev clang-tools
    - uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: 0.13.0
    - uses: extractions/setup-just@v2
    - uses: KyleMayes/install-llvm-action@v2
      with:
        version: "17"
        env: false
        directory: ${{ github.workspace }}/llvm
    - name: Check Zig ENV
      shell: bash
      run: zig env
    - name: Build libgit2, zlib
      shell: bash
      run: |
        echo CC="${{ github.workspace }}/scripts/zig-cc" >> $GITHUB_ENV
        echo CXX="${{ github.workspace }}/scripts/zig-cxx" >> $GITHUB_ENV
        just install-libgit2 && just build-libgit2
        just install-zlib && just build-zlib
    - name: Run zig fmt
      shell: bash
      run: zig fmt --check .
    - name: Pull DataRace Bench
      shell: bash
      run: |
        git clone https://github.com/LLNL/dataracebench.git
    - uses: cachix/install-nix-action@v27
      shell: bash
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/setup-node@v4
      shell: bash
      with:
        corepack-enable: true
        node-version: 22
    - name: Corepack check
      shell: bash
      run: |
        corepack enable
        cd ${{ github.workspace }}
        corepack prepare
