name: Set Up
description: Install Zig, Alpine, libgit2, zlib, libclang
runs:
  using: composite
  steps:
    - name: Setup Base ENV
      shell: sh
      run: |
        sudo apt-get update
        sudo apt-get install wget tar gzip bash git curl file autoconf automake cmake ninja-build
    - uses: goto-bus-stop/setup-zig@v2.2.0
    - uses: extractions/setup-just@v2    
    - name: Check Zig ENV
      shell: bash
      run: zig env
    - name: Build libgit2, zlib
      shell: bash
      run: |
        just install-libgit2 && just build-libgit2
        just install-zlib && just build-zlib
    - name: Run zig fmt
      shell: bash
      run: zig fmt --check .
    - name: Pull DataRace Bench
      shell: bash
      run: |
        git clone https://github.com/LLNL/dataracebench.git
