name: Git clone C library
description: Git clone Micro Benchmarks
runs:
  using: composite
  steps:
    - uses: extractions/setup-just@v2
    - name: Pull Micro Benchmarks
      shell: bash
      run: |
        # Repo on github which star in 2000..5000
        just fetch-micros
