name: Git clone C library
description: Git clone Micro Benchmarks
runs:
  using: composite
  steps:
    - uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: 0.13.0
    - uses: extractions/setup-just@v2
    - uses: KyleMayes/install-llvm-action@v2
      with:
        version: "17"
        env: false
        directory: ${{ github.workspace }}/llvm
    - name: Check Zig ENV
      shell: bash
      run: zig env
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Pull Micro Benchmarks
      shell: bash
      run: |
        # Repo on github which star in 2000..5000
        git clone https://github.com/axboe/fio
        git clone https://github.com/microsoft/Detours
        git clone https://github.com/phusion/passenger
        git clone https://github.com/NVIDIA/DALI
        git clone https://github.com/lballabio/QuantLib
        git clone https://github.com/aircrack-ng/aircrack-ng
        git clone https://github.com/vmg/redcarpet
        git clone https://github.com/emcrisostomo/fswatch
        git clone https://github.com/wjakob/instant-meshes
        git clone https://github.com/jagt/clumsy
        git clone https://github.com/leethomason/tinyxml2
        git clone https://github.com/zcash/zcash
        git clone https://github.com/cuberite/cuberite
        git clone https://github.com/itinance/react-native-fs
        git clone https://github.com/Zelda64Recomp/Zelda64Recomp
        git clone https://github.com/immortalwrt/immortalwrt
        git clone https://github.com/visit1985/mdp
        git clone https://github.com/jbeder/yaml-cpp
        git clone https://github.com/gnuradio/gnuradio
        git clone https://github.com/mlpack/mlpack
        git clone https://github.com/guanzhi/GmSSL
        git clone https://github.com/NVIDIA/cccl
        git clone https://github.com/littlefs-project/littlefs
        git clone https://github.com/antirez/sds
        git clone https://github.com/rhasspy/piper
