name: Install Ocaml
description: Install Zig, Alpine, libgit2, zlib, libclang
runs:
  using: composite
  steps:
    - name: Setup Opam
      shell: bash
      run: |
        apk add opam m4 make gcc g++ musl-dev linux-headers
    - name: Initialize OPAM
      shell: bash
      run: opam init --disable-sandboxing --kind=local
    - name: Update OPAM Repository
      shell: bash
      run: opam update
    - name: Install OCaml Compiler
      shell: bash
      run: |
        opam switch create 4.13.1
        eval $(opam env)
        env >> $GITHUB_ENV
        ocaml --version
    - name: Check OCaml
      shell: bash
      run: ocaml --version
