name : Baseline

on:
  workflow_call:

jobs:
  run-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: alpine:3.19
    uses: ./.github/workflows/setup-env.yml
    steps:
      - name: build the test cases, record time by using meson --profile
        run: |
          just build-examples
      
