name: build deps and binary
on:
  workflow_call:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build Binary
        # run: zig build -Doptimize=ReleaseSafe --verbose-link --search-prefix ${{ github.workspace }}/llvm/lib
        # zig build -Doptimize=ReleaseSafe --verbose-link --search-prefix /usr/lib/llvm-18
        run: |
          just install-llvm
          just build-all
      - name: Build tests
        run: |
          just config-examples
          just build-examples
      - name: Run Test
        # run: zig build test --search-prefix ${{ github.workspace }}/llvm/lib
        run: |
          just run-analysis-test
