name: build deps and binary

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: alpine:3.19
    uses: ./.github/workflows/setup-env.yml
    steps:
      - name: Build
        run: zig build -Doptimize=ReleaseSafe -Dtarget=native-native-musl

      # TODO
      # Upload to Release

      # TODO
      # - name: Run zig test
      #   run: zig test
