name: Coccinelle
on:
  workflow_call:
jobs:
  coccinelle-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: alpine:3.19
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/ocaml
      - name: install coccinelle
        run: |
          eval $(opam env)
          opam init --compiler 4.14.1
          opam install coccinelle
