name: Coderrect
on:
  workflow_call:
jobs:
  coderrect-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Coderrect Scan
        uses: coderrect-inc/coderrect-github-action@main
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential cmake ninja-build clang
      - run: just config-examples
      - name: run coderrect
        run: |
          cd examples-build
          coderrect -t ninja
