name: Coderrect
on:
  workflow_call:
jobs:
  coderrect-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential cmake ninja-build clang
      - run: just config-examples
      - name: install coderrect
        run: |
          wget https://coderrect.com/x/coderrect-linux-1.1.3.tar.gz
          tar zxf coderrect-linux-1.1.3.tar.gz
          export PATH=$PWD/coderrect-linux-1.1.3/bin:$PATH 
          env >> $GITHUB_ENV
      - name: run coderrect
        run: |
          coderrect examples-build/wrong_atomic_cpp,examples-build/wrong_atomic_2_cpp,examples-build/wrong_atomic_2,examples-build/wrong_atomic,examples-build/protect_by_lock,examples-build/privileges,examples-build/paramaters,examples-build/infi_recur,examples-build/global,examples-build/dead_lock,examples-build/correct_atomic,examples-build/correct ninja -C examples-build
