name : Coderrect

on:
  workflow_call:

jobs:
  coderrect:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: alpine:3.19
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: coderrect scan
        uses: coderrect-inc/coderrect-github-action@v1.2
        with:
          buildCommand: "just build-examples"
