name: Coderrect
on:
  workflow_call:
jobs:
  coderrect-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential cmake ninja-build clang
      - run: just config-examples
      - name: coderrect scan
        uses: coderrect-inc/coderrect-github-action@v1.2
        with:
          buildCommand: "ninja -C examples-build"
          cleanCommand: ""
