name : Coverity

on:
  workflow_call:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: alpine:3.19
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup-env.yml

      - name: setup coverity
        run: |
          just install-coverity
    # TODO
