name: Coverity
on:
  workflow_call:
jobs:
  coverity-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: setup coverity
        run: |
          just install-coverity
    # TODO
