name: Frama-C
on:
  workflow_call:
jobs:
  frama-c-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: alpine:3.19
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/ocaml
      - name: install Frama-C
        run: |
          opam init --compiler 4.14.1
          opam install frama-c --yes
          eval $(opam env)
          frama-c --version
