name: IKOS
on:
  workflow_call:
jobs:
  ikos-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: run ikos
        run: |
          just config-examples
          ikos-scan just build-examples
