name : IKOS

on:
  workflow_call:

jobs:
  ikos-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            allow-unfree = true

      - run: echo "NIXPKGS_ALLOW_UNFREE=1" >> $GITHUB_ENV

      - name: install ikos
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix profile install nixpkgs#ikos
      
      - name: run ikos
        run: |
          just config-examples
          ikos-scan just build-examples
