name : IKOS

on:
  workflow_call:

jobs:
  ikos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: install ikos
        run: brew install nasa-sw-vnv/core/ikos
      
      - name: run ikos
        run: |
          just config-examples
          ikos-scan just build-examples
