name: IKOS
on:
  workflow_call:
jobs:
  ikos-baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ikos
        run: |
          brew install nasa-sw-vnv/core/ikos
      - name: run ikos
        run: |
          yes | ikos-scan just config-examples
          yes | ikos-scan just build-examples
