name: CI
on: [push]
jobs:
  zig-build:
    uses: ./.github/workflows/build.yml
  infer:
    uses: ./.github/workflows/infer-racerd.yml
  clang-static-analyzer:
    uses: ./.github/workflows/clang-static-analyzer.yml
  coderrect:
    uses: ./.github/workflows/coderrect.yml
  coverity:
    uses: ./.github/workflows/coverity.yml
  parasoft-test:
    uses: ./.github/workflows/parasoft-test.yml
  ikos:
    uses: ./.github/workflows/ikos.yml
  frama-c:
    uses: ./.github/workflows/frama-c.yml
  coccinelle:
    uses: ./.github/workflows/coccinelle.yml
