on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2.2.0

    - name: Add llvm pacakge source
      run: |
        deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main
        deb-src http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-17 main

    - name: install libclang
      run: |
        apt-get install clang-17 clang-tools-17 clang-17-doc libclang-common-17-dev libclang-17-dev libclang1-17 clang-format-17 python3-clang-17 clangd-17 clang-tidy-17
    
    - name: install libgit2
      run: |
        apt-get install libgit2-dev
        
    - name: Build
      run: zig build -Doptimize=ReleaseSafe
      
    - name: Run tests
      run: zig build test
