name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0

      - name: Check Zig ENV
        run: zig env

      - name: Run zig fmt
        run: zig fmt --check .
     
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh all
          
      - name: Verify LLVM installation, libclang and clang
        run: |  
          clang --version
          find /usr -e 'libclang.a' && find /usr -e 'libssl.a' && find /usr -e 'libgit2.a'

      - name: Check for libclang binary
        run: |
          if find /usr -maxdepth 1 -type f -print0 | xargs -0 file | grep -q "libssl"; then
            echo "Static binary found"
          else
            echo "No static binary found"
          fi

      - name: install CMake, Ninja
        run: |
          sudo apt-get update
          sudo apt-get install cmake ninja-build gcc --yes

      - name: Init
        run: |
          echo "Fetch libgit2, compile, Fetch Prebuilt LLVM(TODO)"
          just init

      - name: Build
        run: zig build -Doptimize=ReleaseSafe
