name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0

      - name: Check Zig ENV
        run: zig env

      - name: Run zig fmt
        run: zig fmt --check .
     
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh all
          
      - name: Verify LLVM installation, libclang and clang
        run: |  
          clang-18 --version
          find /usr -name 'libclang.a' && find /usr -name 'libssl.a' && find /usr -name 'libgit2.a'

      - name: install CMake, Ninja
        run: |
          sudo apt-get update
          sudo apt-get install cmake ninja-build gcc --yes

      - name: Init
        run: |
          echo "Fetch libgit2, compile, Fetch Prebuilt LLVM(TODO)"
          just init

      - name: Build
        run: zig build -Doptimize=ReleaseSafe
