name: Run RWOP on the Micro Benchmarks
on:
  workflow_call:
jobs:
  micros:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build Binary
        # run: zig build -Doptimize=ReleaseSafe --verbose-link --search-prefix ${{ github.workspace }}/llvm/lib
        run: zig build -Doptimize=ReleaseSafe --verbose-link --search-prefix /usr/lib/llvm-18
      - name: Install Bin
        run: sudo cp zig-out/bin/analysis /usr/local/bin/analysis
      - uses: ./.github/actions/fetch-micro-bench
      - name: Run Micro Benchmarks on fio
        run: |
          cd fio
          analysis rwop
      - name: Run Micro Benchmarks on Detours
        run: |
          cd detours
          analysis rwop
      - name: Run Micro Benchmarks on passenger
        run: |
          cd passenger
          analysis rwop
      - name: Run Micro Benchmarks on DALI
        run: |
          cd DALI
          analysis rwop
      - name: Run Micro Benchmarks on QuantLib
        run: |
          cd QuantLib
          analysis rwop
